Api caller
svbrodersen/CSC207_project pull request #21
Opened 2023-11-08 21:26 UTC by svbrodersen

Api caller class and interface with simple unit tests for the two methods.

2023-11-09 16:17 UTC, rohanbrohan requested changes
Looks good. Slight typo on file name for OMDBCaller but other than that I see no issues.

2023-11-09 16:17 UTC, rohanbrohan commented on src/utility/OMDPCaller.java
Slight typo with file name, should be OMDBCaller.java

2023-11-10 00:26 UTC, svbrodersen commented
fixed the typo

2023-11-10 02:50 UTC, Alex732004 reviewed
Api caller looks good

2023-11-10 02:50 UTC, Alex732004 approved these changes

2023-11-10 02:51 UTC, Alex732004 approved these changes
Typo is fixed

2023-11-10 03:04 UTC, rohanbrohan approved these changes

2023-11-10 03:04 UTC, merged